version: '2'
run:
  timeout: 5m
  tests: false
linters:
  settings:
    errcheck:
      exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
    revive:
      max-open-files: 2048
      severity: error
      rules:
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
        - maxLitCount: '3'
          allowStrs: '""'
          allowInts: 0,1,2
          allowFloats: 0.0,0.,1.0,1.,2.0,2.
      - name: argument-limit
        severity: warning
        disabled: false
        arguments:
        - 4
      - name: atomic
        severity: warning
        disabled: false
      - name: banned-characters
        severity: warning
        disabled: false
        arguments:
        - Ω
        - Σ
        - σ
        - '7'
      - name: blank-imports
        severity: warning
        disabled: false
      - name: bool-literal-in-expr
        severity: warning
        disabled: false
      - name: cognitive-complexity
        severity: warning
        disabled: false
        arguments:
        - 60
      - name: comment-spacings
        severity: warning
        disabled: false
        arguments:
        - nosec
      - name: confusing-naming
        severity: warning
        disabled: false
      - name: confusing-results
        severity: warning
        disabled: false
      - name: constant-logical-expr
        severity: warning
        disabled: false
      - name: cyclomatic
        severity: warning
        disabled: false
        arguments:
        - 20
      - name: datarace
        severity: warning
        disabled: false
      - name: deep-exit
        severity: warning
        disabled: false
      - name: defer
        severity: warning
        disabled: false
        arguments:
        - - call-chain
          - loop
      - name: dot-imports
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: early-return
        severity: warning
        disabled: false
        arguments:
        - preserveScope
      - name: empty-block
        severity: warning
        disabled: false
      - name: empty-lines
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: errorf
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false
        arguments:
        - checkPrivateReceivers
        - sayRepetitiveInsteadOfStutters
      - name: flag-parameter
        severity: warning
        disabled: false
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments:
        - 4
      - name: function-length
        severity: warning
        disabled: false
        arguments:
        - 75
        - 0
      - name: get-return
        severity: warning
        disabled: false
      - name: identical-branches
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: import-shadowing
        severity: warning
        disabled: false
      - name: line-length-limit
        severity: warning
        disabled: false
        arguments:
        - 150
      - name: modifies-parameter
        severity: warning
        disabled: false
      - name: modifies-value-receiver
        severity: warning
        disabled: false
      - name: nested-structs
        severity: warning
        disabled: false
      - name: optimize-operands-order
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: true
      - name: range
        severity: warning
        disabled: false
      - name: range-val-in-closure
        severity: warning
        disabled: false
      - name: range-val-address
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false
      - name: redefines-builtin-id
        severity: warning
        disabled: false
      - name: string-of-int
        severity: warning
        disabled: false
      - name: superfluous-else
        severity: warning
        disabled: false
        arguments:
        - preserveScope
      - name: time-equal
        severity: warning
        disabled: false
      - name: time-naming
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
        - - ID
        - - VM
        - - upperCaseConst: true
      - name: var-declaration
        severity: warning
        disabled: false
      - name: unconditional-recursion
        severity: warning
        disabled: false
      - name: unexported-naming
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false
      - name: unhandled-error
        severity: warning
        disabled: false
      - name: unnecessary-stmt
        severity: warning
        disabled: false
      - name: unreachable-code
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
        - allowRegex: ^_
      - name: unused-receiver
        severity: warning
        disabled: false
        arguments:
        - allowRegex: ^_
      - name: useless-break
        severity: warning
        disabled: false
      - name: waitgroup-by-value
        severity: warning
        disabled: false
  default: none
  enable:
  - revive
  - gosec
  - errorlint
  exclusions:
    generated: disable
    paths:
    - redfish/provider/data_source_redfish_system_boot.go
formatters:
  enable:
  - gofmt
  - gofumpt
output:
  sort-order:
  - file
